### ISSUE TITLE
Swallowed exceptions

### ISSUE THREAD

**Issue by Namek** [timjansen/minified.js#54]
Awhile development, sometimes features silently stop working and it needs a static analysis of code to find out what's happening.

When a callback (in`.request()` or in a promise) throws an error, it is catched and no one notices that. Is there a way to globally handle it and/or rethrow it?

**Comment by timjansen** [comment]
No, unfortunately not in Minified. The next-gen Nia (which is not making a
lot of progress in the last few months unfortunately) will be much better
in that regard. It has both better reporting, as well as global handlers.
But I have no immediate plans for Minified, as that would bring it over the
4kb limit.

Tim

**Comment by Namek** [comment]
Is that try/catch necessary? Can I fork the project and just remove it? Tracking errors is really hard and time consuming because of this. And, during development, some errors are not found straightaway which increases "bugfix" commits.

**Comment by timjansen** [comment]
It's required for compliance with the Promises/A+ spec. It's quite possible
that the project works fine without it, never tried it.

Tim

**Comment by Namek** [comment]
Is it really compliant to swallow error when there is no error handler?

**Comment by timjansen** [comment]
It's swallowed in the sense of not passing the exception through to the
calling thread, and thus it won't show in the browser's console. It's not
swallowed from the Promise/A+ perspective, as the promise returned by the
error()/then() method will report the exception as a rejected promise. The
spec does not define what's reported on the console.

I am aware of the issue, but unfortunately a bit short on time in the last
months. If I can find the time, I am going to create a Minified 1.1 as an
intermediate release which will contain a solution for this and the other
most important issues (but it will be also a bit over >4kb).

Tim

**Comment by Namek** [comment]
To me, efficient work and software stability is much more important than smallness of the library.

I didn't have much time to look too deply into the code (BTW building system is bit weird) but what I would suggest is a logic like:

```
if hasErrorHandler then
    try { operation() } catch err { errorHandler(err) }
else
  operation();
```

Do you think that's possible?

**Comment by timjansen** [comment]
Assuming you use the full version, there should be two places where
exceptions would have to be reported:
https://github.com/timjansen/minified.js/blob/master/src/minified-extras-full-src.js
Lines 255 and 263. If you'd just add a console.log() in there, you would
have error reporting for all exceptions that are thrown by any exception
handler.

Really throwing the exception to let it pass through to the calling thread,
so it will interoperate with the browser's debugger and so on, is not that
easy though. You don't want *every* exception to be reported, as some are
already handled by a proper error handler. The Nia implementation of
promise() therefore tracks which error handlers have been registered for a
particular promise, and only rethrows exception when there is no error
handler for them (
https://github.com/niajs/nia/blob/master/src/nia-headless-src.js starting
line 1417).

I can understand your view of smallness being not that important. That's
why I started Nia as replacement.

The build system is so complex because of the builder and the
double-optimization. That's also something I addressed with Nia (and the
reason why it has no builder).

Tim

**Comment by timjansen** [comment]
Checked in a new promise implementation for Minified 1.1: In the Web module, all exceptions thrown by then() handlers are re-thrown into the callling thread. In the complete version, it will do the same, but only if there is no rejection handler registered.

**Comment by Namek** [comment]
Thanks! I just tried that and it works. Unfortunately, original stacktrace is lost.
